name: Build Android Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Build apk
        run: flutter build apk

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: |
            build/app/outputs/flutter-apk